import { baseAnimal } from './animal.js';

const Goat = function (canvas) {
  this.color = 'silver';
  this.pixels = [
    { x: -5, y: -6 },
    { x: -5, y: -5 },
    { x: -5, y: -4 },
    { x: -3, y: -6 },
    { x: -3, y: -5 },
    { x: -3, y: -4 },
    { x: -6, y: -3 },
    { x: -5, y: -3 },
    { x: -4, y: -3 },
    { x: -3, y: -3 },
    { x: -2, y: -3 },
    { x: -5, y: -2 },
    { x: -4, y: -2 },
    { x: -3, y: -2 },
    { x: -2, y: -2 },
    { x: -1, y: -2 },
    { x: 0, y: -2 },
    { x: 1, y: -2 },
    { x: 2, y: -2 },
    { x: 3, y: -2 },
    { x: 4, y: -2 },
    { x: -5, y: -1 },
    { x: -4, y: -1 },
    { x: -3, y: -1 },
    { x: -2, y: -1 },
    { x: -1, y: -1 },
    { x: 0, y: -1 },
    { x: 1, y: -1 },
    { x: 2, y: -1 },
    { x: 3, y: -1 },
    { x: 4, y: -1 },
    { x: -4, y: 0 },
    { x: -2, y: 0 },
    { x: -1, y: 0 },
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 2, y: 0 },
    { x: 3, y: 0 },
    { x: 4, y: 0 },
    { x: 5, y: 0 },
    { x: -4, y: 1 },
    { x: -2, y: 1 },
    { x: -1, y: 1 },
    { x: 0, y: 1 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
    { x: 3, y: 1 },
    { x: 4, y: 1 },
    { x: -2, y: 2 },
    { x: 0, y: 2 },
    { x: 2, y: 2 },
    { x: 4, y: 2 },
    { x: -2, y: 3 },
    { x: 0, y: 3 },
    { x: 2, y: 3 },
    { x: 4, y: 3 },
    { x: -2, y: 4 },
    { x: 0, y: 4 },
    { x: 2, y: 4 },
    { x: 4, y: 4 },
  ];
  this.init(canvas);
};

Object.setPrototypeOf(Goat.prototype, baseAnimal);

export {
  Goat,
};
